/**
 * LeaveFlow CI/CD Production Build Script
 * ============================================================
 * Run automatically by GitHub Actions on every push to main.
 * Also run locally via: node build.js  (reads .env)
 *
 * What this script does:
 *   1. Reads LEAVEFLOW_API_URL from env / .env file
 *   2. Writes js/config.js  (frontend consumes this to know the API URL)
 *   3. Stamps sw.js CACHE_VERSION with a fresh unix timestamp
 *      → browser detects sw.js byte change → installs new SW → clears old cache
 *   4. Logs the build version so CI logs confirm the stamp
 */

const fs   = require('fs');
const path = require('path');

// ── 1. Resolve API URL ─────────────────────────────────────────────
let apiUrl = process.env.LEAVEFLOW_API_URL || '';

if (!apiUrl && fs.existsSync(path.join(__dirname, '.env'))) {
  const lines = fs.readFileSync(path.join(__dirname, '.env'), 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
      const eqIdx = trimmed.indexOf('=');
      if (trimmed.slice(0, eqIdx).trim() === 'LEAVEFLOW_API_URL') {
        apiUrl = trimmed.slice(eqIdx + 1).trim().replace(/^['"]|['"]$/g, '');
        break;
      }
    }
  }
}

// ── 2. Write js/config.js ─────────────────────────────────────────
const CONFIG_FILE = path.join(__dirname, 'js', 'config.js');
const configDir   = path.dirname(CONFIG_FILE);
if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });

fs.writeFileSync(CONFIG_FILE,
  `// Auto-generated by build.js — do not edit manually\n` +
  `window.LEAVEFLOW_API_URL = "${apiUrl}";\n`
);
console.log(`[BUILD] config.js → API URL: ${apiUrl ? '(configured)' : '(empty — PWA will show config warning)'}`);

// ── 3. Stamp sw.js with fresh build timestamp ─────────────────────
//
//  The service worker uses:
//      const CACHE_VERSION = 'leaveflow-v2';
//  build.js replaces the version string with a unix timestamp so the
//  browser detects a byte-change and triggers the SW update flow.
//
//  Pattern matched: const CACHE_VERSION = '...';
//
const SW_FILE = path.join(__dirname, 'sw.js');

if (!fs.existsSync(SW_FILE)) {
  console.error('[BUILD] ✗ sw.js not found — service worker will NOT be updated');
  process.exit(1);
}

const timestamp   = Date.now();
const versionTag  = `leaveflow-v${timestamp}`;
let swContent     = fs.readFileSync(SW_FILE, 'utf8');

const swPatched = swContent.replace(
  /const CACHE_VERSION = ['"][^'"]*['"];/,
  `const CACHE_VERSION = '${versionTag}';`
);

if (swPatched === swContent) {
  console.error('[BUILD] ✗ Could not find CACHE_VERSION in sw.js — check the pattern');
  process.exit(1);
}

fs.writeFileSync(SW_FILE, swPatched);
console.log(`[BUILD] sw.js → CACHE_VERSION stamped: ${versionTag}`);
console.log(`[BUILD] ✓ Build complete. Deployed version: ${versionTag}`);
